# This file was generated by GoReleaser. DO NOT EDIT.
cask "sand" do
  version "0.0.13"

  on_macos do
    on_intel do
      sha256 "185f7286cd617f7f97a943dc5b646ee52a146f49bfd2b825bdf5ee2c278d7bfd"
      url "https://github.com/banksean/sand/releases/download/v#{version}/sand_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "686f60caa2c5b1035c463acde7ed647e07cffa016caa53fc9309fec79ec00de7"
      url "https://github.com/banksean/sand/releases/download/v#{version}/sand_darwin_arm64.tar.gz"
    end
  end

  name "sand"
  desc "Local development sandbox containers"
  homepage "https://github.com/banksean/sand"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sand"
  binary "sandd"

  # No zap stanza required

end
